Add responsive styles for 120px-320px-600px
fndmt-org/sentirama pull request #12
Opened 2021-11-01 09:11 UTC by rmi8092

This PR includes every changes to get Sentirama ready for mobile and medium devices

2021-11-07 19:02 UTC, pableco requested changes
Super Rafa!! 
Si quieres lo vemos juntos. Mañana tengo oftalmologo. Me quedaron varios pixeles que tendríamos que pasar a ritmo, etc. Lo hablamos, genial!

2021-11-07 19:02 UTC, pableco commented on src/components/Styles/basicVariables.styles.js
> +    iconsSizeXXL: '20.2rem',
esto parece más una imagen que un icono.

2021-11-07 19:02 UTC, pableco commented on src/components/Styles/iconSizes.styles.js
> +        width: ${({ theme }) => theme.iconsSizeXXL};
🤔

2021-11-08 18:12 UTC, merged

2021-11-08 18:20 UTC, rmi8092 commented on src/components/Mood/AddMood/addMood.styles.jsx
> +            border-radius: 50%;
Done!

2021-11-08 18:21 UTC, rmi8092 commented on src/components/Mood/AddMood/addMood.styles.jsx
> +                border-radius: 94px;
Done!

2021-11-08 18:21 UTC, rmi8092 commented on src/components/Mood/AddMood/addMood.styles.jsx
> +                border-radius: 50%;
Done!

2021-11-08 18:23 UTC, rmi8092 commented on src/components/Mood/AddMood/addMood.styles.jsx
> +    gap: 27px;
Done!

2021-11-08 18:23 UTC, rmi8092 commented on src/components/Mood/AddMood/addMood.styles.jsx
> +        gap: 58px;
Done!

2021-11-08 18:25 UTC, rmi8092 commented on src/components/Mood/LayoutStyles/moodLayout.styles.jsx
> +            top: 10px;
Done!

2021-11-08 18:36 UTC, rmi8092 commented on src/components/Mood/LayoutStyles/moodLayout.styles.jsx
> +                top: 135px;
Done!

2021-11-08 18:40 UTC, rmi8092 commented on src/components/Mood/LayoutStyles/moodLayout.styles.jsx
> +                ${(props) => props.top ? `top: 20px` : `top: 135px`}
Done!

2021-11-08 18:40 UTC, rmi8092 commented on src/components/Mood/MoodResults/moodResults.styles.jsx
>  import themeDefaultImport from '../../Styles/basicVariables.styles';
Vale, lo vemos mas adelante si quieres ;-)

2021-11-08 18:46 UTC, rmi8092 commented on src/components/Styles/basicVariables.styles.js
> +    iconsSizeXXL: '20.2rem',
lo tuve que crear para el selector inicial de mood en tamaño responsive 320px
![image](https://user-images.githubusercontent.com/11421940/140799722-5c28241a-ee73-44f5-9f07-630911eb847f.png)

2021-11-08 18:47 UTC, rmi8092 commented on src/components/Styles/iconSizes.styles.js
> +        width: ${({ theme }) => theme.iconsSizeXXL};
Esto también lo tuve que crear para los botones de selector de mood comentados arriba